---
- name: Get my public IP
  ipify_facts:

- name: install packages
  with_items: "{{ jabber_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart jabber

- name: enable jabber service
  template:
    src: ejabberd.j2
    dest: /etc/rc.conf.d/ejabberd

- name: install cert updater
  copy:
    src: update_certs.sh
    dest: /usr/local/bin/update_certs.sh
    mode: 0755

- name: create certs dir
  file:
    name: "/usr/local/etc/ejabberd/certs"
    mode: 0700
    owner: ejabberd
    group: ejabberd
    state: directory

- name: create upload dir
  file:
    name: "/var/cache/ejabberd"
    mode: 0700
    owner: ejabberd
    group: ejabberd
    state: directory

- name: convert cert from letsencrypt
  command: /usr/local/bin/update_certs.sh "{{ jabber_domain }}"
  args:
    creates: "/usr/local/etc/ejabberd/certs/{{ jabber_domain }}.key"

- name: configure jabber
  template:
    src: ejabberd.yml.j2
    dest: /usr/local/etc/ejabberd/ejabberd.yml
  notify:
    - restart jabber
